const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const PORT=process.env.PORT||3000, DB=path.join(__dirname,'data','db.json'), PUBLIC=__dirname
const sessions=new Map();
function ensure(){if(!fs.existsSync(path.dirname(DB)))fs.mkdirSync(path.dirname(DB),{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:[],swipes:[],messages:[]},null,2));}
function db(){ensure();return JSON.parse(fs.readFileSync(DB,'utf8'))} function save(x){fs.writeFileSync(DB,JSON.stringify(x,null,2))}
const id=()=>crypto.randomUUID(), hash=p=>crypto.createHash('sha256').update(p).digest('hex'), token=()=>crypto.randomBytes(32).toString('hex');
const safe=u=>{const{x}=u;return x}; function safeUser(u){const{x}=u;const {passwordHash,...r}=u;return r}
function age(dob){const d=new Date(dob),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return a}
function key(a,b){return[a,b].sort().join(':')}
function json(res,status,obj){const s=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(s)}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)})}
function auth(req){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const uid=sessions.get(t);const d=db();return {d,u:d.users.find(x=>x.id===uid),t}}
function distance(a,b){if(!a.lat||!a.lng||!b.lat||!b.lng)return null;const r=Math.PI/180,R=6371,d1=(b.lat-a.lat)*r,d2=(b.lng-a.lng)*r,x=Math.sin(d1/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(d2/2)**2;return Math.round(R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)))}
async function api(req,res,p){
 try{
  if(req.method==='POST'&&p==='/api/register'){const b=await body(req),d=db();if(!b.name||!b.email||!b.password||!b.dob||!b.gender||!b.interestedIn)return json(res,400,{error:'Name, email, password, DOB, gender and preference are required'});if(b.password.length<6)return json(res,400,{error:'Password must be at least 6 characters'});if(d.users.some(u=>u.email===String(b.email).toLowerCase().trim()))return json(res,409,{error:'Email already registered'});const u={id:id(),name:String(b.name).trim(),email:String(b.email).toLowerCase().trim(),passwordHash:hash(b.password),dob:b.dob,age:age(b.dob),gender:b.gender,interestedIn:b.interestedIn,bio:String(b.bio||'').trim(),photo:b.photo||`https://i.pravatar.cc/700?u=${encodeURIComponent(b.email)}`,createdAt:new Date().toISOString()};d.users.push(u);save(d);const t=token();sessions.set(t,u.id);return json(res,200,{token:t,user:safeUser(u)})}
  if(req.method==='POST'&&p==='/api/login'){const b=await body(req),d=db(),u=d.users.find(x=>x.email===String(b.email||'').toLowerCase().trim());if(!u||u.passwordHash!==hash(b.password||''))return json(res,401,{error:'Invalid email or password'});const t=token();sessions.set(t,u.id);return json(res,200,{token:t,user:safeUser(u)})}
  const a=auth(req);if(!a.u)return json(res,401,{error:'Authentication required'});const d=a.d,u=a.u;
  if(req.method==='POST'&&p==='/api/logout'){sessions.delete(a.t);return json(res,200,{ok:true})}
  if(req.method==='GET'&&p==='/api/me')return json(res,200,{user:safeUser(u)});
  if(req.method==='PUT'&&p==='/api/me'){const b=await body(req);for(const k of ['name','dob','gender','interestedIn','bio','photo'])if(b[k]!==undefined)u[k]=b[k];u.age=age(u.dob);save(d);return json(res,200,{user:safeUser(u)})}
  if(req.method==='GET'&&p==='/api/discover'){const q=url.parse(req.url,true).query,seen=new Set(d.swipes.filter(s=>s.from===u.id).map(s=>s.to));let list=d.users.filter(x=>x.id!==u.id&&!seen.has(x.id)&&x.age>=+(q.minAge||18)&&x.age<=+(q.maxAge||100)&&(x.interestedIn==='everyone'||x.interestedIn===u.gender)&&(u.interestedIn==='everyone'||u.interestedIn===x.gender));return json(res,200,{profiles:list.slice(0,50).map(x=>({...safeUser(x),distanceKm:distance(u,x)}))})}
  if(req.method==='POST'&&p==='/api/swipe'){const b=await body(req);if(!b.to||!['like','pass','superlike'].includes(b.action))return json(res,400,{error:'Invalid swipe'});if(b.to===u.id||!d.users.some(x=>x.id===b.to))return json(res,404,{error:'Profile not found'});if(d.swipes.some(s=>s.from===u.id&&s.to===b.to))return json(res,409,{error:'Already swiped'});d.swipes.push({id:id(),from:u.id,to:b.to,action:b.action,createdAt:new Date().toISOString()});const matched=b.action!=='pass'&&d.swipes.some(s=>s.from===b.to&&s.to===u.id&&s.action!=='pass');save(d);return json(res,200,{matched})}
  if(req.method==='GET'&&p==='/api/matches'){const pairs=new Set();for(const s of d.swipes.filter(s=>s.action!=='pass'))if(d.swipes.some(x=>x.from===s.to&&x.to===s.from&&x.action!=='pass'))pairs.add(key(s.from,s.to));const out=[];for(const k of pairs){const ids=k.split(':'),oid=ids[0]===u.id?ids[1]:ids[1]===u.id?ids[0]:null;if(!oid)continue;const o=d.users.find(x=>x.id===oid),m=d.messages.filter(x=>key(x.from,x.to)===key(u.id,oid));if(o)out.push({id:o.id,name:o.name,age:o.age,photo:o.photo,bio:o.bio,lastMessage:m.at(-1)?.text||'',lastAt:m.at(-1)?.createdAt||null})}out.sort((x,y)=>String(y.lastAt).localeCompare(String(x.lastAt)));return json(res,200,{matches:out})}
  const mm=p.match(/^\/api\/matches\/([^/]+)\/messages$/);if(mm){const oid=mm[1],o=d.users.find(x=>x.id===oid);if(!o)return json(res,404,{error:'User not found'});const matched=d.swipes.some(s=>s.from===u.id&&s.to===oid&&s.action!=='pass')&&d.swipes.some(s=>s.from===oid&&s.to===u.id&&s.action!=='pass');if(!matched)return json(res,403,{error:'You are not matched'});if(req.method==='GET')return json(res,200,{messages:d.messages.filter(x=>key(x.from,x.to)===key(u.id,oid))});const b=await body(req),text=String(b.text||'').trim();if(!text||text.length>1000)return json(res,400,{error:'Invalid message'});const m={id:id(),from:u.id,to:oid,text,createdAt:new Date().toISOString()};d.messages.push(m);save(d);return json(res,200,{message:m})}
  json(res,404,{error:'Not found'});
 }catch(e){console.error(e);json(res,500,{error:'Server error'})}
}
function seed(){const d=db();if(d.users.length)return;[['Aisha','aisha@connection.demo','female','male','Coffee, books and weekend road trips.'],['Maya','maya@connection.demo','female','everyone','Doctor by day, photographer by weekend.'],['Arjun','arjun@connection.demo','male','female','Gym, travel and discovering great food.'],['Riya','riya@connection.demo','female','male','Music lover. Looking for genuine conversations.'],['Kabir','kabir@connection.demo','male','everyone','Tech enthusiast who loves hiking.'],['Ananya','ananya@connection.demo','female','everyone','Kindness, curiosity and chai.']].forEach(x=>d.users.push({id:id(),name:x[0],email:x[1],passwordHash:hash('demo123'),dob:'1999-01-15',age:27,gender:x[2],interestedIn:x[3],bio:x[4],photo:`https://i.pravatar.cc/700?u=${x[0]}`,createdAt:new Date().toISOString()}));save(d)}
ensure();seed();
http.createServer(async(req,res)=>{const p=url.parse(req.url).pathname;if(p.startsWith('/api/'))return api(req,res,p);let f=p==='/'?'/index.html':p;f=path.join(PUBLIC,f);if(!f.startsWith(PUBLIC)||!fs.existsSync(f)||fs.statSync(f).isDirectory())return res.writeHead(404).end('Not found');const ext=path.extname(f);const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}).listen(PORT,()=>console.log(`Connection running at http://localhost:${PORT}`));
